///* =========================================================
// * ====                   WARNING                        ===
// * =========================================================
// * The code in this tab has been generated from the GUI form
// * designer and care should be taken when editing this file.
// * Only add/edit code inside the event handlers i.e. only
// * use lines between the matching comment tags. e.g.

// void myBtnEvents(GButton button) { //_CODE_:button1:12356:
//     // It is safe to enter your event code here  
// } //_CODE_:button1:12356:
 
// * Do not rename this tab!
// * =========================================================
// */

//synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:userControls:917188:
//  appc.background(230);
//} //_CODE_:userControls:917188:

//public void columnSlider(GCustomSlider source, GEvent event) { //_CODE_:columnsSlider:969015:
//columns = columnsSlider.getValueI();
//} //_CODE_:columnsSlider:969015:

//public void rowSlider(GCustomSlider source, GEvent event) { //_CODE_:rowsSlider:897435:
//  rows = rowsSlider.getValueI();
//} //_CODE_:rowsSlider:897435:

//public void buildingButton(GButton source, GEvent event) { //_CODE_:buildButton:282539:
//  buildingType = "building";
  
//  println("buildButton - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:buildButton:282539:

//public void busButton(GButton source, GEvent event) { //_CODE_:busButt:663197:
//  buildingType = "bus";
  
//  println("busButt - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:busButt:663197:

//public void storeButton(GButton source, GEvent event) { //_CODE_:stores:793439:
//  buildingType = "store";
  
//  println("stores - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:stores:793439:

//public void roadButton(GButton source, GEvent event) { //_CODE_:Road:238039:
//  buildingType = "road";
//  println("Road - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:Road:238039:

//public void submitButton(GButton source, GEvent event) { //_CODE_:done:640477:
//  println("done - GButton >> GEvent." + event + " @ " + millis());
//} //_CODE_:done:640477:

//public void storeName(GTextArea source, GEvent event) { //_CODE_:storename:702325:
//  println("storename - GTextArea >> GEvent." + event + " @ " + millis());
//} //_CODE_:storename:702325:



//// Create all the GUI controls. 
//// autogenerated do not edit
//public void createGUI(){
//  G4P.messagesEnabled(false);
//  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
//  G4P.setMouseOverEnabled(false);
//  surface.setTitle("Sketch Window");
//  userControls = GWindow.getWindow(this, "User Controls ", 0, 0, 230, 250, JAVA2D);
//  userControls.noLoop();
//  userControls.setActionOnClose(G4P.KEEP_OPEN);
//  userControls.addDrawHandler(this, "win_draw1");
//  columnsSlider = new GCustomSlider(userControls, 1, 46, 100, 40, "blue18px");
//  columnsSlider.setLimits(5, 2, 20);
//  columnsSlider.setNumberFormat(G4P.INTEGER, 0);
//  columnsSlider.setOpaque(false);
//  columnsSlider.addEventHandler(this, "columnSlider");
//  columnlabel = new GLabel(userControls, -24, 25, 143, 20);
//  columnlabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
//  columnlabel.setText("Adjust Column #");
//  columnlabel.setOpaque(false);
//  userControl = new GLabel(userControls, 37, 5, 134, 20);
//  userControl.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
//  userControl.setText("User Controls ");
//  userControl.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
//  userControl.setOpaque(false);
//  rowsSlider = new GCustomSlider(userControls, 117, 46, 100, 40, "red_yellow18px");
//  rowsSlider.setLimits(2, 2, 20);
//  rowsSlider.setNumberFormat(G4P.INTEGER, 0);
//  rowsSlider.setLocalColorScheme(GCScheme.RED_SCHEME);
//  rowsSlider.setOpaque(false);
//  rowsSlider.addEventHandler(this, "rowSlider");
//  rowLabel = new GLabel(userControls, 129, 27, 81, 20);
//  rowLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
//  rowLabel.setText("Adjust Row #");
//  rowLabel.setLocalColorScheme(GCScheme.RED_SCHEME);
//  rowLabel.setOpaque(false);
//  buildButton = new GButton(userControls, 13, 95, 80, 30);
//  buildButton.setText("Building");
//  buildButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
//  buildButton.addEventHandler(this, "buildingButton");
//  busButt = new GButton(userControls, 12, 134, 80, 30);
//  busButt.setText("Bus Button ");
//  busButt.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
//  busButt.addEventHandler(this, "busButton");
//  stores = new GButton(userControls, 12, 172, 80, 30);
//  stores.setText("My Store");
//  stores.setLocalColorScheme(GCScheme.RED_SCHEME);
//  stores.addEventHandler(this, "storeButton");
//  Road = new GButton(userControls, 11, 212, 80, 30);
//  Road.setText("Road");
//  Road.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
//  Road.addEventHandler(this, "roadButton");
//  done = new GButton(userControls, 121, 194, 80, 30);
//  done.setText("SUBMIT");
//  done.addEventHandler(this, "submitButton");
//  storename = new GTextArea(userControls, 104, 96, 120, 80, G4P.SCROLLBARS_HORIZONTAL_ONLY);
//  storename.setPromptText("What is the name of your store?");
//  storename.setOpaque(true);
//  storename.addEventHandler(this, "storeName");
//  userControls.loop();
//}

//// Variable declarations 
//// autogenerated do not edit
//GWindow userControls;
//GCustomSlider columnsSlider; 
//GLabel columnlabel; 
//GLabel userControl; 
//GCustomSlider rowsSlider; 
//GLabel rowLabel; 
//GButton buildButton; 
//GButton busButt; 
//GButton stores; 
//GButton Road; 
//GButton done; 
//GTextArea storename; 
