/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:userControl:709282:
  appc.background(230);
} //_CODE_:userControl:709282:

public void columnsSlider(GCustomSlider source, GEvent event) { //_CODE_:colSlider:688321:
  cols = colSlider.getValueI();

  // recreate layout (because the columns of grid have changed)
  layout = new Layout(rows, cols);

  //clear population so no Person objects reference old layout while it's being rebuilt (prevents null exception)
  population = null;

  // Reset store-related values (makes it so that you can still place only one store)
  layout.storeplaced = false;
  layout.storeRow = -1;
  layout.storeCol = -1;
  layout.storeName = "";
  
  layout.structureType = 5;  // Reset mode after recreation
//population = null;   
  //If currently building the layout then the controls are visible
  screenType = "building";     
  userControl.setVisible(true);
  displayControl.setVisible(false);
} //_CODE_:colSlider:688321:

public void rowSlider(GCustomSlider source, GEvent event) { //_CODE_:rSlider:837005:
  rows = rSlider.getValueI();

  // recreate layout (because the columns of grid have changed)
  layout = new Layout(rows, cols);

  //clear population so no Person objects reference old layout while it's being rebuilt (prevents null exception)
  population = null;

  // Reset store-related values (makes it so that you can still place only one store)
  layout.storeplaced = false;
  layout.storeRow = -1;
  layout.storeCol = -1;
  layout.storeName = "";
  
  layout.structureType = 5;  // Reset mode after recreation
//population = null;   
  //If currently bulding the layout then the controls are visible
  screenType = "build";     
  userControl.setVisible(true);
  displayControl.setVisible(false);
} //_CODE_:rSlider:837005:

public void buildingButton(GButton source, GEvent event) { //_CODE_:buildButton:634112:
  layout.structureType = 4;
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:buildButton:634112:

public void busstopButton(GButton source, GEvent event) { //_CODE_:busButton:942668:
  layout.structureType = 2;
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:busButton:942668:

public void mystoreButton(GButton source, GEvent event) { //_CODE_:storeButton:224962:
  layout.structureType = 1;
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:storeButton:224962:

public void roadsButton(GButton source, GEvent event) { //_CODE_:roadButton:708872:
  layout.structureType = 3;
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:roadButton:708872:

public void submit(GButton source, GEvent event) { //_CODE_:submitButton:798579:
  if (layout.storeplaced) {
    screenType = "display";
    generatePopulation();
    userControl.setVisible(false);
    displayControl.setVisible(true);
    layout.buttonClicked = false;
  }
  else{
    println("No store placed.");
  }
} //_CODE_:submitButton:798579:

public void delete(GButton source, GEvent event) { //_CODE_:deleteButton:591698:
  //Getting rid of structure type (nothing assigned)
  layout.structureType = -1;
  layout.buttonClicked = true;
  println("Delete mode");
} //_CODE_:deleteButton:591698:

public void NameofStore(GTextField source, GEvent event) { //_CODE_:storeName:458681:
  String entered = storeName.getText().trim();

  if (entered.length() > 0) {
    //println("User entered store name: " + entered);
    layout.storeName = entered;
  } else {
    println("No text entered.");
  }
} //_CODE_:storeName:458681:

public void populationSlider(GCustomSlider source, GEvent event) { //_CODE_:populationNum:692818:
  populationNumber = populationNum.getValueI();
  println("populationNum - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:populationNum:692818:

synchronized public void displayControls(PApplet appc, GWinData data) { //_CODE_:displayControl:510305:
} //_CODE_:displayControl:510305:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  userControl = GWindow.getWindow(this, "userControls", 0, 0, 300, 350, JAVA2D);
  userControl.noLoop();
  userControl.setActionOnClose(G4P.KEEP_OPEN);
  userControl.addDrawHandler(this, "win_draw1");
  usercontrols = new GLabel(userControl, 79, 5, 122, 20);
  usercontrols.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  usercontrols.setText("User Controls");
  usercontrols.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  usercontrols.setOpaque(false);
  colSlider = new GCustomSlider(userControl, 14, 72, 100, 40, "red_yellow18px");
  colSlider.setLimits(5, 5, 20);
  colSlider.setNumberFormat(G4P.INTEGER, 0);
  colSlider.setLocalColorScheme(GCScheme.RED_SCHEME);
  colSlider.setOpaque(false);
  colSlider.addEventHandler(this, "columnsSlider");
  collabel = new GLabel(userControl, -1, 41, 124, 20);
  collabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  collabel.setText("Adjust Column #");
  collabel.setLocalColorScheme(GCScheme.RED_SCHEME);
  collabel.setOpaque(false);
  rSlider = new GCustomSlider(userControl, 161, 71, 100, 40, "blue18px");
  rSlider.setLimits(5, 5, 20);
  rSlider.setNumberFormat(G4P.INTEGER, 0);
  rSlider.setOpaque(false);
  rSlider.addEventHandler(this, "rowSlider");
  rowlabel = new GLabel(userControl, 163, 41, 80, 20);
  rowlabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  rowlabel.setText("Adjust Row #");
  rowlabel.setOpaque(false);
  buildButton = new GButton(userControl, 14, 129, 80, 30);
  buildButton.setText("Building");
  buildButton.addEventHandler(this, "buildingButton");
  busButton = new GButton(userControl, 13, 168, 80, 30);
  busButton.setText("Bus Stop");
  busButton.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  busButton.addEventHandler(this, "busstopButton");
  storeButton = new GButton(userControl, 13, 211, 80, 30);
  storeButton.setText("My Store ");
  storeButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  storeButton.addEventHandler(this, "mystoreButton");
  roadButton = new GButton(userControl, 13, 254, 80, 30);
  roadButton.setText("Road");
  roadButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  roadButton.addEventHandler(this, "roadsButton");
  submitButton = new GButton(userControl, 153, 312, 80, 30);
  submitButton.setText("SUBMIT");
  submitButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  submitButton.addEventHandler(this, "submit");
  deleteButton = new GButton(userControl, 60, 312, 80, 30);
  deleteButton.setText("DELETE");
  deleteButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  deleteButton.addEventHandler(this, "delete");
  storeName = new GTextField(userControl, 160, 255, 120, 30, G4P.SCROLLBARS_NONE);
  storeName.setOpaque(true);
  storeName.addEventHandler(this, "NameofStore");
  storeLabel = new GLabel(userControl, 160, 205, 126, 40);
  storeLabel.setText("What is the name of your store?");
  storeLabel.setOpaque(false);
  populationNum = new GCustomSlider(userControl, 161, 147, 100, 40, "grey_blue");
  populationNum.setLimits(20, 20, 100);
  populationNum.setNumberFormat(G4P.INTEGER, 0);
  populationNum.setOpaque(false);
  populationNum.addEventHandler(this, "populationSlider");
  popLabel = new GLabel(userControl, 160, 124, 137, 20);
  popLabel.setText("Change Population Size");
  popLabel.setOpaque(false);
  displayControl = GWindow.getWindow(this, "Display Controls ", 0, 0, 150, 200, JAVA2D);
  displayControl.noLoop();
  displayControl.setActionOnClose(G4P.KEEP_OPEN);
  displayControl.addDrawHandler(this, "displayControls");
  userControl.loop();
  displayControl.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow userControl;
GLabel usercontrols; 
GCustomSlider colSlider; 
GLabel collabel; 
GCustomSlider rSlider; 
GLabel rowlabel; 
GButton buildButton; 
GButton busButton; 
GButton storeButton; 
GButton roadButton; 
GButton submitButton; 
GButton deleteButton; 
GTextField storeName; 
GLabel storeLabel; 
GCustomSlider populationNum; 
GLabel popLabel; 
GWindow displayControl;
