/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:userControl:709282:
  appc.background(230);
} //_CODE_:userControl:709282:

public void columnsSlider(GCustomSlider source, GEvent event) { //_CODE_:colSlider:688321:
  cols = colSlider.getValueI();
  //reupdating the layout 
  layout = new Layout(rows, cols); 
} //_CODE_:colSlider:688321:

public void rowSlider(GCustomSlider source, GEvent event) { //_CODE_:rSlider:837005:
  rows = rSlider.getValueI();
  layout = new Layout(rows, cols); 
} //_CODE_:rSlider:837005:

public void buildingButton(GButton source, GEvent event) { //_CODE_:buildButton:634112:
  layout.structureType = 4;  
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:buildButton:634112:

public void busstopButton(GButton source, GEvent event) { //_CODE_:busButton:942668:
  layout.structureType = 2;  
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:busButton:942668:

public void mystoreButton(GButton source, GEvent event) { //_CODE_:storeButton:224962:
  layout.structureType = 1;  
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:storeButton:224962:

public void roadsButton(GButton source, GEvent event) { //_CODE_:roadButton:708872:
  layout.structureType = 3;  
  layout.buttonClicked = true;
  println("Building mode selected");
} //_CODE_:roadButton:708872:

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  userControl = GWindow.getWindow(this, "userControls", 0, 0, 250, 250, JAVA2D);
  userControl.noLoop();
  userControl.setActionOnClose(G4P.KEEP_OPEN);
  userControl.addDrawHandler(this, "win_draw1");
  usercontrols = new GLabel(userControl, 52, 3, 122, 20);
  usercontrols.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  usercontrols.setText("User Controls");
  usercontrols.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  usercontrols.setOpaque(false);
  colSlider = new GCustomSlider(userControl, 8, 45, 100, 40, "red_yellow18px");
  colSlider.setLimits(5, 5, 20);
  colSlider.setNumberFormat(G4P.INTEGER, 0);
  colSlider.setLocalColorScheme(GCScheme.RED_SCHEME);
  colSlider.setOpaque(false);
  colSlider.addEventHandler(this, "columnsSlider");
  collabel = new GLabel(userControl, -5, 28, 124, 20);
  collabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  collabel.setText("Adjust Column #");
  collabel.setLocalColorScheme(GCScheme.RED_SCHEME);
  collabel.setOpaque(false);
  rSlider = new GCustomSlider(userControl, 122, 48, 100, 40, "blue18px");
  rSlider.setLimits(5, 5, 20);
  rSlider.setNumberFormat(G4P.INTEGER, 0);
  rSlider.setOpaque(false);
  rSlider.addEventHandler(this, "rowSlider");
  rowlabel = new GLabel(userControl, 131, 29, 80, 20);
  rowlabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  rowlabel.setText("Adjust Row #");
  rowlabel.setOpaque(false);
  buildButton = new GButton(userControl, 12, 97, 80, 30);
  buildButton.setText("Building");
  buildButton.addEventHandler(this, "buildingButton");
  busButton = new GButton(userControl, 11, 136, 80, 30);
  busButton.setText("Bus Stop");
  busButton.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  busButton.addEventHandler(this, "busstopButton");
  storeButton = new GButton(userControl, 11, 175, 80, 30);
  storeButton.setText("My Store ");
  storeButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  storeButton.addEventHandler(this, "mystoreButton");
  roadButton = new GButton(userControl, 10, 212, 80, 30);
  roadButton.setText("Road");
  roadButton.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  roadButton.addEventHandler(this, "roadsButton");
  userControl.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow userControl;
GLabel usercontrols; 
GCustomSlider colSlider; 
GLabel collabel; 
GCustomSlider rSlider; 
GLabel rowlabel; 
GButton buildButton; 
GButton busButton; 
GButton storeButton; 
GButton roadButton; 
